// Central government schemes — researched Sept 2026
export const CENTRAL = [
{
 id:"dpiit", name:"DPIIT Startup Recognition", abbr:"DPIIT", body:"DPIIT, Ministry of Commerce & Industry",
 type:["compliance"], stage:["idea","early","growth"], sector:["all"], amt:"Free · gateway to most benefits", amtL:0,
 student:true, dpiit:false, status:"open", ease:1, tier:"top", since:"2026-02",
 sum:"The official 'startup' tag. Most central benefits — tax holiday, CGSS, fund-of-funds money, IPR rebates and procurement relaxations — only unlock once you hold this certificate. The February 2026 framework doubled the turnover limit and created a new Deep Tech Startup category.",
 ben:["Unlocks Section 140 tax holiday, CGSS, FoF 2.0-backed AIFs, SIPP fee rebates and GeM relaxations","Turnover limit raised from ₹100 crore to ₹200 crore (G.S.R. 108(E), 4 Feb 2026)","New Deep Tech Startup category: recognition for up to 20 years and ₹300 crore turnover","Cooperative societies can now be recognised, alongside companies, LLPs and partnership firms"],
 elig:["Private limited company, LLP, registered partnership firm or cooperative society","Up to 10 years from incorporation (20 years for deep tech startups)","Annual turnover below ₹200 crore in every year since incorporation (₹300 crore for deep tech)","Working on innovation or improvement of a product, process or service, or a scalable business model"],
 docs:["inc","pan","kyc","deck","ip"],
 steps:["Create an account on the Startup India portal (or the National Single Window System)","Fill in the recognition form: entity details, sector, and a short note on what is innovative","Upload the incorporation certificate and a pitch deck or website link","Submit; recognition is usually issued within a few working days, with a certificate number you will quote everywhere else"],
 link:"https://www.startupindia.gov.in/content/sih/en/startupgov/startup_recognition_page.html",
 stacks:["sec140","cgss","sipp","procure"], verified:"Verified Sep 2026 against the 4 Feb 2026 notification coverage"
},
{
 id:"sec140", name:"Startup Tax Holiday (Section 140, formerly 80-IAC)", abbr:"Sec 140", body:"CBDT & DPIIT Inter-Ministerial Board",
 type:["tax"], stage:["early","growth"], sector:["all"], amt:"100% profit deduction for 3 years", amtL:0,
 student:false, dpiit:true, status:"open", ease:2, tier:"top", since:"2026-04",
 sum:"Eligible startups pay no income tax on profits for any 3 consecutive years out of their first 10. Since 1 April 2026 the benefit sits in Section 140 of the Income-tax Act, 2025 (it was Section 80-IAC under the 1961 Act).",
 ben:["100% deduction of profits for 3 consecutive years of your choosing within the first 10","Available to startups incorporated up to 31 March 2030","Applications are reviewed within about 120 days under the revised process"],
 elig:["DPIIT-recognised private limited company or LLP","Incorporated between 1 April 2016 and 31 March 2030","Needs a separate Inter-Ministerial Board (IMB) certificate — DPIIT recognition alone is not enough","Turnover cap per the Income-tax Act, 2025 conditions (confirm the current limit with your CA)"],
 docs:["dpiit","inc","fin","deck","ip","board"],
 steps:["Log in to the Startup India portal and open the 80-IAC / Section 140 application form","Explain the innovation, revenue model and employment impact; attach financials","The IMB reviews the application and may ask for clarifications","Once certified, claim the deduction in your company's income-tax return for the years you choose"],
 link:"https://www.startupindia.gov.in/content/sih/en/form80iac.html",
 stacks:["dpiit","angel"], verified:"Verified Sep 2026 (PIB, May 2025; Income-tax Act 2025 renumbering)"
},
{
 id:"angel", name:"Angel Tax Abolished", abbr:"No angel tax", body:"Ministry of Finance",
 type:["tax"], stage:["idea","early","growth"], sector:["all"], amt:"No tax on share premium", amtL:0,
 student:false, dpiit:false, status:"auto", ease:1, tier:"major", since:"2024-07",
 sum:"The old 'angel tax' — tax on share premium above fair value under Section 56(2)(viib) — was repealed from assessment year 2025-26 and was not carried into the Income-tax Act, 2025. Raising equity at a premium no longer triggers this tax for any company.",
 ben:["No tax on funds raised above fair market value from resident or foreign investors","Removes the need for DPIIT angel-tax exemption filings (Form 2)"],
 elig:["Applies automatically to all closely held companies","Other anti-abuse rules (unexplained credits, below-market transfers) still apply — keep investor KYC and valuation reports"],
 docs:["cap","board"],
 steps:["Nothing to apply for — keep a valuation report and investor KYC on file for each round","Report the allotment in your MCA filings as usual"],
 link:"https://www.incometaxindia.gov.in",
 stacks:["fof2","sec140"], verified:"Verified Sep 2026"
},
{
 id:"taxrelief", name:"Other Startup Tax Reliefs (ESOP deferral, loss carry-forward)", abbr:"Tax reliefs", body:"Ministry of Finance & DPIIT",
 type:["tax"], stage:["early","growth"], sector:["all"], amt:"Deferred ESOP tax; losses carried forward", amtL:0,
 student:false, dpiit:true, status:"auto", ease:2, tier:"more", since:"2020-04",
 sum:"Employees of eligible startups can defer tax on ESOPs until they sell shares, leave, or five years pass. Eligible startups can also carry forward losses despite ownership changes, as long as the original shareholders continue.",
 ben:["ESOP perquisite tax deferred — employees don't pay tax on paper gains at exercise","Business losses carried forward even when shareholding changes, subject to conditions"],
 elig:["DPIIT-recognised startups holding the IMB tax certificate (for ESOP deferral)","Original shareholders must continue to hold shares for the loss carry-forward relief"],
 docs:["dpiit","cap","board"],
 steps:["Obtain the IMB certificate (see the Section 140 entry)","Have your CA apply the deferral in TDS on ESOPs and the carry-forward in your return"],
 link:"https://www.incometaxindia.gov.in/income-from-business/profession-taxation-of-start-ups",
 stacks:["sec140"], verified:"Summary of standing provisions; confirm section numbers under the 2025 Act with your CA"
},
{
 id:"sipp", name:"Startup IP Protection (SIPP): patent & trademark fee rebates", abbr:"SIPP", body:"DPIIT & Office of CGPDTM (IP India)",
 type:["ipr"], stage:["idea","early","growth"], sector:["all"], amt:"80% off patent fees, 50% off trademark fees", amtL:0,
 student:true, dpiit:true, status:"open", ease:1, tier:"top", since:"2016-01",
 sum:"Recognised startups file patents at a fraction of the normal cost, get free help from empanelled facilitators, and can ask for expedited examination — often cutting grant time from years to months.",
 ben:["80% rebate on patent filing fees and 50% on trademark fees","Government-paid patent and trademark facilitators — you pay only statutory fees","Expedited patent examination on request"],
 elig:["DPIIT-recognised startup (students' patents can use the startup's recognition once incorporated)"],
 docs:["dpiit","ip","kyc"],
 steps:["Pick a facilitator from the IP India list of empanelled patent/trademark agents","File with IP India selecting the 'startup' applicant category and attach your DPIIT certificate","Request expedited examination (Form 18A) if you need a faster grant"],
 link:"https://ipindia.gov.in",
 stacks:["dpiit","msme-innov"], verified:"Standing scheme; verified active Sep 2026"
},
{
 id:"procure", name:"Selling to Government: GeM Startup Runway & procurement relaxations", abbr:"GeM", body:"DPIIT, Dept of Expenditure & GeM",
 type:["procurement"], stage:["early","growth"], sector:["all"], amt:"Waived turnover, experience and EMD rules", amtL:0,
 student:false, dpiit:true, status:"open", ease:1, tier:"major", since:"2016-01",
 sum:"Central ministries and PSUs can buy from recognised startups without asking for prior turnover or experience, and startups are exempt from earnest money deposits. GeM's Startup Runway lets you list innovative products that don't yet fit standard catalogue categories.",
 ben:["Exemption from prior turnover and prior experience criteria in public tenders (quality and technical specs still apply)","Exemption from Earnest Money Deposit (EMD)","List new-to-market products on GeM via Startup Runway"],
 elig:["DPIIT-recognised startup","Product or service must meet the tender's technical specifications"],
 docs:["dpiit","inc","pan","udyam"],
 steps:["Register as a seller on GeM using your DPIIT certificate","Tag your listings as startup products or apply through Startup Runway for novel items","Quote the startup exemption clause when bidding for tenders"],
 link:"https://gem.gov.in",
 stacks:["dpiit","udyam","treds"], verified:"Standing policy; verified Sep 2026"
},
{
 id:"selfcert", name:"Self-Certification under Labour & Environment Laws", abbr:"Self-cert", body:"DPIIT, Ministry of Labour, MoEFCC",
 type:["compliance"], stage:["idea","early"], sector:["all"], amt:"Fewer inspections for 3–5 years", amtL:0,
 student:false, dpiit:true, status:"open", ease:1, tier:"more", since:"2016-01",
 sum:"Recognised startups can self-certify compliance with key labour and environment laws, so routine inspections are skipped in the early years unless there's a credible complaint.",
 ben:["Self-certification under labour laws for up to 5 years","Startups in 'white category' industries are exempt from certain environment inspections"],
 elig:["DPIIT-recognised startup"],
 docs:["dpiit"],
 steps:["Submit the self-declaration on the Shram Suvidha / state labour portal","Keep your registers and records updated in case of a complaint-triggered inspection"],
 link:"https://www.startupindia.gov.in",
 stacks:["dpiit"], verified:"Standing provision"
},
{
 id:"exit", name:"Fast-Track Exit for Startups (IBC)", abbr:"Fast exit", body:"Ministry of Corporate Affairs / IBBI",
 type:["compliance"], stage:["early","growth"], sector:["all"], amt:"Wind up within ~90 days", amtL:0,
 student:false, dpiit:false, status:"open", ease:2, tier:"more", since:"2016-01",
 sum:"Startups with simple debt structures can be wound up on a fast track, so failed ventures don't trap founders in years of proceedings.",
 ben:["Insolvency resolution on a fast track for eligible startups","Frees founders to start again quickly"],
 elig:["Startups meeting the fast-track criteria under the Insolvency and Bankruptcy Code (simple debt structure, specified turnover limits)"],
 docs:["inc","fin","board"],
 steps:["Consult an insolvency professional to check fast-track eligibility","File with the adjudicating authority as advised"],
 link:"https://ibbi.gov.in",
 stacks:[], verified:"Standing provision"
},
{
 id:"sisfs", name:"Startup India Seed Fund Scheme", abbr:"SISFS", body:"DPIIT (via selected incubators)",
 type:["grant","loan"], stage:["idea","early"], sector:["all"], amt:"Up to ₹20 L grant + ₹50 L debt", amtL:70,
 student:false, dpiit:true, status:"closed", statusNote:"Closed to startups on 31 May 2026; no successor announced yet", ease:2, tier:"major", since:"2021-04",
 sum:"India's flagship seed scheme: up to ₹20 lakh as a grant for proof of concept and prototypes, plus up to ₹50 lakh as debt or convertible instruments for market entry, disbursed through selected incubators. The ₹945 crore corpus has been allocated and applications closed in 2026.",
 ben:["Up to ₹20 lakh grant for PoC, prototype and product trials","Up to ₹50 lakh via convertible debentures or debt for market entry and scaling"],
 elig:["DPIIT-recognised startup incorporated not more than 2 years before applying","Must not have received more than ₹10 lakh from other central/state schemes"],
 docs:["dpiit","inc","deck","prop","kyc","cap"],
 steps:["Watch the Startup India portal for a new scheme cycle","Meanwhile, use NIDHI-SSP, SAMRIDH and state seed grants, which are still open"],
 link:"https://seedfund.startupindia.gov.in/",
 stacks:[], verified:"Verified Sep 2026: deadline was extended to 31 May 2026, then closed"
},
{
 id:"fof2", name:"Startup India Fund of Funds 2.0", abbr:"FoF 2.0", body:"DPIIT (SIDBI as implementing agency)",
 type:["equity"], stage:["early","growth"], sector:["all","deeptech","manufacturing"], amt:"₹10,000 cr corpus via VC funds", amtL:0,
 student:false, dpiit:true, status:"open", ease:3, tier:"top", since:"2026-04",
 sum:"The government doesn't invest in startups directly; it commits capital to SEBI-registered venture funds (AIFs), which then invest in DPIIT-recognised startups. Version 2.0 (approved 14 Feb 2026; guidelines 25 Apr 2026) earmarks money for deep tech, micro-VC funds for early-growth startups, and tech-led manufacturing.",
 ben:["More VC money for deep tech, manufacturing and early-growth startups beyond the metros","Four fund segments: deep tech, micro VC, innovative manufacturing, and sector-agnostic","FoF 1.0 backed 145 AIFs that invested ₹25,500+ crore in 1,370+ startups"],
 elig:["DPIIT-recognised startup raising equity from an AIF that has FoF commitment","The AIF — not you — applies to SIDBI; you pitch the AIF like any other investor"],
 docs:["dpiit","deck","cap","fin"],
 steps:["Find AIFs backed by the Fund of Funds (SIDBI publishes the list)","Pitch those funds directly; mention your DPIIT recognition","Close the round on normal VC terms"],
 link:"https://sidbivcf.in/en",
 stacks:["cgss","sec140","angel"], verified:"Verified Sep 2026 (PIB, 14 Feb & 25 Apr 2026)"
},
{
 id:"cgss", name:"Credit Guarantee Scheme for Startups", abbr:"CGSS", body:"DPIIT & NCGTC",
 type:["guarantee","loan"], stage:["early","growth"], sector:["all"], amt:"Collateral-free loans up to ₹20 cr", amtL:2000,
 student:false, dpiit:true, status:"open", ease:2, tier:"top", since:"2025-05",
 sum:"The government guarantees most of a lender's risk, so banks, NBFCs and venture-debt funds can lend to startups without collateral. The cover limit was doubled to ₹20 crore per borrower in May 2025.",
 ben:["Guarantee up to ₹20 crore per borrower (was ₹10 crore)","85% of default covered on loans up to ₹10 crore; 75% above that","Annual guarantee fee cut to 1% for startups in 27 Make in India champion sectors","Covers term loans, working capital and venture debt"],
 elig:["DPIIT-recognised startup","Not in default to any lender","Loan from a scheduled bank, NBFC, all-India financial institution or SEBI-registered AIF"],
 docs:["dpiit","inc","fin","bank","deck","cap"],
 steps:["Approach your bank, NBFC or venture-debt fund and ask for a CGSS-covered loan","The lender appraises you and applies to NCGTC for the guarantee","Pay the annual guarantee fee (usually passed on by the lender)"],
 link:"https://www.startupindia.gov.in/content/sih/en/credit-guarantee-scheme-for-startups.html",
 stacks:["dpiit","fof2","treds"], verified:"Verified Sep 2026 (PIB, 9 May 2025)"
},
{
 id:"network", name:"Startup India Hub, Investor Connect & MAARG Mentoring", abbr:"Startup India Hub", body:"DPIIT / Invest India",
 type:["support"], stage:["idea","early","growth"], sector:["all"], amt:"Free", amtL:0,
 student:true, dpiit:false, status:"open", ease:1, tier:"more", since:"2016-01",
 sum:"Free national platforms: a single portal for queries and scheme applications, an investor-matching platform run with SIDBI, and the MAARG portal to book mentors by sector.",
 ben:["Investor Connect: match with VCs and angels","MAARG: sector mentors for early-stage founders","Help desk and challenge listings from ministries and corporates"],
 elig:["Open to all founders; some features need DPIIT recognition"],
 docs:["deck"],
 steps:["Create a free Startup India profile","Complete your startup profile to appear in Investor Connect","Book mentors through MAARG"],
 link:"https://www.startupindia.gov.in",
 stacks:["dpiit","silp"], verified:"Standing platform"
},
{
 id:"silp", name:"Startup India Learning Programme", abbr:"Learning programme", body:"DPIIT / Invest India",
 type:["support"], stage:["idea"], sector:["all"], amt:"Free online course + certificate", amtL:0,
 student:true, dpiit:false, status:"open", ease:1, tier:"more", since:"2017-01",
 sum:"A free, self-paced online course taught by successful Indian founders covering ideation, fundraising, legal basics and go-to-market. A good first step for students.",
 ben:["Free lessons from founders and investors","Certificate on completion"],
 elig:["Anyone — no incorporation needed"],
 docs:[],
 steps:["Sign up on the Startup India portal","Complete the modules at your own pace"],
 link:"https://www.startupindia.gov.in",
 stacks:["network","prayas"], verified:"Standing programme"
},
{
 id:"nsa", name:"National Startup Awards", abbr:"NSA", body:"DPIIT",
 type:["challenge"], stage:["early","growth"], sector:["all"], amt:"Cash prize + national recognition", amtL:10,
 student:false, dpiit:true, status:"calls", statusNote:"5th edition results announced 12 Mar 2026; watch for the next call", ease:3, tier:"more", since:"2026-03",
 sum:"Annual awards recognising outstanding startups and ecosystem enablers across sectors. Winners get prize money (₹10 lakh in recent editions), investor and government introductions, and pilot opportunities.",
 ben:["Prize money for winners (₹10 lakh in recent editions)","Visibility with ministries, corporates and investors"],
 elig:["DPIIT-recognised startup meeting the edition's age and revenue criteria"],
 docs:["dpiit","deck","fin"],
 steps:["Apply on the Startup India portal when the edition opens","Shortlisted startups present to a jury"],
 link:"https://www.startupindia.gov.in/content/sih/en/nsa2025.html",
 stacks:["network"], verified:"Verified Sep 2026 (5th edition results, Mar 2026)"
},
{
 id:"rdi", name:"Research, Development & Innovation (RDI) Fund", abbr:"RDI Fund", body:"ANRF / DST (via TDB and BIRAC as fund managers)",
 type:["loan","equity"], stage:["early","growth"], sector:["deeptech","bio","climate","tech","agri"], amt:"Up to 50% of project cost; loans at 3–4%", amtL:0,
 student:false, dpiit:false, status:"open", ease:3, tier:"top", since:"2026-02",
 sum:"A ₹1 lakh crore, six-year fund for private R&D in strategic and sunrise sectors. Startups at technology readiness level (TRL) 4 and above get long-term, low-cost loans or equity through second-level fund managers — TDB for most sectors, BIRAC for biotech. The first cheques went out in May 2026.",
 ben:["Long-term loans at 3–4% interest, repayable over 12–15 years with a moratorium","Equity up to 25% of assistance, or soft loans convertible to equity","Covers up to 50% of assessed project cost (relaxable in strategic sectors)"],
 elig:["Indian company, LLP or partnership controlled by resident Indian citizens; HQ in India","Technology at TRL 4 or higher","Priority sectors: energy transition, deep tech, AI, biotech & medtech, digital economy and agriculture"],
 docs:["inc","dpr","fin","ip","cap","proto","board"],
 steps:["Check sector fit on the RDI portal","Apply through TDB's e-techcom portal (or BIRAC for biotech)","Technical and financial due diligence, then milestone-based tranches"],
 link:"https://rdifund.anrf.gov.in/",
 stacks:["tdb","big","dli"], verified:"Verified Sep 2026 (TDB SLFM page; first disbursements 13 May 2026)"
},
{
 id:"tdb", name:"Technology Development Board Assistance", abbr:"TDB", body:"Technology Development Board, DST",
 type:["loan","equity"], stage:["early","growth"], sector:["deeptech","manufacturing","bio","climate"], amt:"Soft loans / equity up to 50% of project cost", amtL:0,
 student:false, dpiit:false, status:"open", ease:3, tier:"major", since:"1996-01",
 sum:"TDB funds Indian companies commercialising indigenous or adapted technologies, through soft loans and equity. It also runs themed calls (for example for startups, clean energy and quantum) and is a fund manager for the RDI Fund.",
 ben:["Soft loans on concessional terms and/or equity","Typically up to 50% of the project cost"],
 elig:["Indian company with a technology ready to be commercialised","Promoter contribution for the remaining project cost"],
 docs:["inc","dpr","fin","ip","proto"],
 steps:["Apply on TDB's online portal against an open call or the rolling window","Technical and financial appraisal, then an agreement with milestones"],
 link:"https://tdb.gov.in",
 stacks:["rdi","prayas"], verified:"Standing scheme; verified Sep 2026"
},
{
 id:"indiaai", name:"IndiaAI Compute (subsidised GPUs)", abbr:"IndiaAI Compute", body:"IndiaAI Mission, MeitY",
 type:["compute","subsidy"], stage:["idea","early","growth"], sector:["tech","deeptech"], amt:"38,000+ GPUs at subsidised hourly rates", amtL:0,
 student:true, dpiit:false, status:"open", ease:1, tier:"top", since:"2026-03",
 sum:"Under the ₹10,372 crore IndiaAI Mission, Indian startups, researchers and students can rent high-end GPUs through the AI compute portal at heavily subsidised rates, instead of paying global cloud prices.",
 ben:["Access to a common pool of 38,000+ GPUs","Hourly rates far below market cloud pricing","Also: the AIKosh dataset platform and IndiaAI innovation challenges"],
 elig:["Indian startups, MSMEs, academia and students working on AI"],
 docs:["inc","kyc","prop"],
 steps:["Register on the IndiaAI compute portal","Submit your use case and compute requirement","Get allotted GPU hours and pay the subsidised rate"],
 link:"https://indiaai.gov.in",
 stacks:["samridh","genesis","rdi"], verified:"Verified Sep 2026 (PIB, 25 Mar 2026)"
},
{
 id:"dli", name:"Semicon 2.0 — Design Linked Incentive (DLI)", abbr:"DLI", body:"India Semiconductor Mission, MeitY",
 type:["grant","equity","subsidy"], stage:["early","growth"], sector:["deeptech","manufacturing"], amt:"Was 50% up to ₹15 cr; revamped Sep 2026", amtL:1500,
 student:false, dpiit:false, status:"open", statusNote:"New Semicon 2.0 terms notified week of 9 Sep 2026", ease:3, tier:"major", since:"2026-09",
 sum:"Support for chip-design startups. The 2021 DLI reimbursed up to 50% of eligible design costs (capped at ₹15 crore) plus deployment incentives. The Semicon 2.0 revamp in September 2026 adds government co-investment alongside VCs, royalty-based financing and a 9% deployment-linked incentive on chip sales for five years (capped at ₹30 crore).",
 ben:["Co-investment with VCs above the old ₹15 crore cap","Royalty financing: repay 5% of net product revenue up to 1.5× the support","Deployment incentive of 9% on chip sales for 5 years, up to ₹30 crore","Access to EDA tools and design infrastructure"],
 elig:["Indian startups and MSMEs designing semiconductor ICs, chipsets, SoCs or IP cores"],
 docs:["inc","dpr","fin","ip","cap"],
 steps:["Register on the ISM DLI portal","Submit a design project proposal","Review by ISM, then milestone-linked support"],
 link:"https://chips-dli.gov.in/",
 stacks:["rdi","c2s","fof2"], verified:"Verified Sep 2026 (Business Standard, 9 Sep 2026)"
},
{
 id:"c2s", name:"Chips to Startup (C2S) Programme", abbr:"C2S", body:"MeitY",
 type:["support","fellowship"], stage:["idea"], sector:["deeptech"], amt:"Chip-design training, EDA tools, project funding via institutes", amtL:0,
 student:true, dpiit:false, status:"calls", ease:2, tier:"more", since:"2022-01",
 sum:"Trains engineering students in chip design through participating academic institutions, with access to EDA tools and funding for design projects — a pipeline into semiconductor startups.",
 ben:["Access to industry EDA tools and fabrication runs via your institute","Project-based learning in VLSI and system design"],
 elig:["Students and faculty at participating academic and R&D institutions"],
 docs:["student"],
 steps:["Check whether your college is a C2S participating institute","Join its chip-design project team or course"],
 link:"https://www.meity.gov.in",
 stacks:["dli","prayas"], verified:"Standing programme"
},
{
 id:"ttdf", name:"Telecom Technology Development Fund", abbr:"TTDF", body:"Dept of Telecommunications (Digital Bharat Nidhi)",
 type:["grant"], stage:["early","growth"], sector:["telecom","deeptech"], amt:"R&D grants by call (₹542 cr approved across 136 projects)", amtL:0,
 student:false, dpiit:false, status:"calls", ease:3, tier:"more", since:"2022-10",
 sum:"Funds indigenous telecom R&D — 5G/6G, network equipment, satellite communication, quantum communication — through calls for proposals. Startups can apply alone or in consortia with academia.",
 ben:["Grants for telecom product R&D and pilots","Consortium projects with IITs and R&D labs are encouraged"],
 elig:["Indian startups, MSMEs, academia, R&D institutions and consortia"],
 docs:["inc","dpr","fin","ip"],
 steps:["Watch the TTDF portal for open calls","Submit a proposal matching a call's topic","Technical review, then milestone-based funding"],
 link:"https://ttdf.usof.gov.in/",
 stacks:["rdi"], verified:"Verified Sep 2026 (136 projects, ₹542 cr approved by Dec 2025)"
},
{
 id:"prayas", name:"NIDHI-PRAYAS (prototype grant)", abbr:"PRAYAS", body:"DST — NIDHI programme (via PRAYAS centres at TBIs)",
 type:["grant"], stage:["idea"], sector:["all","deeptech","manufacturing"], amt:"Up to ₹10 lakh", amtL:10,
 student:true, dpiit:false, status:"calls", ease:2, tier:"top", since:"2016-01",
 sum:"The go-to grant for turning an idea into a working prototype — especially hardware. Individuals and students can apply before incorporating a company.",
 ben:["Up to ₹10 lakh to build a prototype or proof of concept","Mentoring, lab and fabrication access at the host incubator"],
 elig:["Students, researchers, innovators or early startups with a technology idea","You don't need to be incorporated","Apply to one PRAYAS centre at a time"],
 docs:["kyc","prop","student","edu"],
 steps:["Find a PRAYAS centre near you on the NIDHI-PRAYAS portal","Apply during its call with a proposal and budget","Pitch to the centre's committee; funds are released in milestones"],
 link:"https://nidhi-prayas.org/",
 stacks:["eir","ssp","sipp"], verified:"Verified Sep 2026 (nidhi.dst.gov.in)"
},
{
 id:"eir", name:"NIDHI-Entrepreneur in Residence (EIR)", abbr:"NIDHI-EIR", body:"DST — NIDHI programme (via EIR centres at TBIs)",
 type:["fellowship"], stage:["idea"], sector:["all"], amt:"₹10,000–₹30,000 a month for up to 12 months", amtL:3.6,
 student:true, dpiit:false, status:"calls", ease:2, tier:"top", since:"2016-01",
 sum:"A monthly stipend so graduates can work full-time on a tech startup idea instead of taking a job, while sitting inside an incubator.",
 ben:["Stipend of ₹10,000–₹30,000 per month","Up to 12 months","Co-working space and mentoring"],
 elig:["Graduates and final-year students pursuing a technology-based idea","Should not hold another fellowship or full-time job at the same time"],
 docs:["kyc","edu","prop"],
 steps:["Apply to a NIDHI-EIR centre (list on the NIDHI-EIR site)","Interview and pitch; selected fellows sign on with the incubator"],
 link:"https://www.nidhi-eir.in",
 stacks:["prayas","ssp"], verified:"Verified Sep 2026 (nidhi.dst.gov.in)"
},
{
 id:"ssp", name:"NIDHI Seed Support Programme", abbr:"NIDHI-SSP", body:"DST — NIDHI programme (via TBIs)",
 type:["grant","equity","loan"], stage:["early"], sector:["all","deeptech"], amt:"Up to ₹1 crore", amtL:100,
 student:false, dpiit:false, status:"calls", ease:3, tier:"top", since:"2016-01",
 sum:"Seed money from DST-supported incubators for startups with a validated technology heading to market. The incubator decides the instrument (grant, debt, equity-linked).",
 ben:["Up to ₹1 crore per startup","Delivered by the incubator with mentoring"],
 elig:["Startup incubated (usually 3+ months) at a participating TBI","Innovative technology with a clear path to market"],
 docs:["inc","deck","prop","incub","cap","proto"],
 steps:["Get incubated at a DST-supported TBI","Apply when your incubator announces an SSP call","Present to the seed committee; sign the investment or grant agreement"],
 link:"https://nidhi.dst.gov.in/nidhissp/",
 stacks:["prayas","eir","incubators"], verified:"Verified Sep 2026 (nidhi.dst.gov.in)"
},
{
 id:"incubators", name:"Get Incubated: TBIs, Atal Incubation Centres & BioNEST", abbr:"Incubators", body:"DST, AIM (NITI Aayog), BIRAC, MeitY",
 type:["incubation"], stage:["idea","early"], sector:["all"], amt:"Subsidised space, labs and mentoring", amtL:0,
 student:true, dpiit:false, status:"open", ease:2, tier:"major", since:"2016-01",
 sum:"Hundreds of government-backed incubators — DST's TBIs, Atal Incubation Centres, Atal Community Innovation Centres in tier-2/3 towns, BIRAC BioNEST, MeitY TIDE centres — offer cheap desks, labs and mentors. Being incubated is the entry ticket to PRAYAS, EIR, SSP, TIDE and many state grants.",
 ben:["Low-cost desks, labs and prototyping facilities","Mentors, investor days and help with scheme applications"],
 elig:["Founders or students with an idea; selection by each incubator"],
 docs:["deck","kyc","prop"],
 steps:["Shortlist incubators strong in your sector (search the Startup India incubator list)","Apply to their cohort call","Sign the incubation agreement"],
 link:"https://www.startupindia.gov.in",
 stacks:["prayas","eir","ssp","tide"], verified:"Standing network"
},
{
 id:"manak", name:"INSPIRE-MANAK Awards (school students)", abbr:"MANAK", body:"DST & National Innovation Foundation",
 type:["grant","challenge"], stage:["idea"], sector:["all"], amt:"₹10,000 per selected idea", amtL:0.1,
 student:true, dpiit:false, status:"calls", ease:1, tier:"more", since:"2017-01",
 sum:"For school students aged 10–15 (Classes 6–10): schools nominate ideas, and selected students get ₹10,000 to build a model, with a chance to reach the national exhibition.",
 ben:["₹10,000 into the student's account for a model","District, state and national exhibitions and mentoring"],
 elig:["School students in Classes 6–10, nominated by their school"],
 docs:["student"],
 steps:["Your school registers on the E-MIAS portal and nominates ideas","Selected students receive the award and build a prototype"],
 link:"https://www.inspireawards-dst.gov.in",
 stacks:["atl"], verified:"Standing programme"
},
{
 id:"tih", name:"Technology Innovation Hubs (NM-ICPS)", abbr:"TIHs", body:"DST — National Mission on Interdisciplinary Cyber-Physical Systems",
 type:["grant","fellowship","incubation"], stage:["idea","early"], sector:["deeptech","tech"], amt:"Startup grants and fellowships, by hub call", amtL:0,
 student:true, dpiit:false, status:"calls", ease:2, tier:"more", since:"2020-01",
 sum:"Twenty-five technology hubs hosted at IITs and other premier institutes each run startup grants, fellowships and challenges in their domain — AI, robotics, data, IoT, quantum and more.",
 ben:["Seed grants and pre-incubation for deep-tech startups","Student and research fellowships in the hub's domain"],
 elig:["Varies by hub and call; many are open to students"],
 docs:["prop","kyc","student"],
 steps:["Find the hub for your domain and follow its calls","Apply with a project proposal"],
 link:"https://dst.gov.in",
 stacks:["prayas","eir"], verified:"Standing programme"
},
{
 id:"big", name:"BIRAC Biotechnology Ignition Grant", abbr:"BIG", body:"BIRAC, Dept of Biotechnology",
 type:["grant"], stage:["idea"], sector:["bio"], amt:"Up to ₹50 lakh", amtL:50,
 student:true, dpiit:false, status:"calls", statusNote:"Two calls a year, opening 1 Jan and 1 Jul (~45 days each)", ease:3, tier:"top", since:"2012-01",
 sum:"India's best-known early-stage biotech grant: up to ₹50 lakh over 18 months to establish proof of concept for a life-sciences idea.",
 ben:["Up to ₹50 lakh grant-in-aid","18-month project with mentoring from BIG partners"],
 elig:["Startups, companies and individual researchers/innovators in biotech, medtech, agri-bio and related areas","Individuals must incorporate before the grant is released"],
 docs:["prop","kyc","inc","ip","edu"],
 steps:["Apply online during the January or July call","Screening, then presentation to the expert committee","Sign the agreement with your BIG partner incubator"],
 link:"https://birac.nic.in/big.php",
 stacks:["birac-seed","sipp","bioe3"], verified:"Verified Sep 2026 (birac.nic.in)"
},
{
 id:"birac-seed", name:"BIRAC SEED Fund", abbr:"BIRAC SEED", body:"BIRAC (via BioNEST partner incubators)",
 type:["equity"], stage:["early"], sector:["bio"], amt:"Up to ₹30 lakh equity", amtL:30,
 student:false, dpiit:false, status:"calls", ease:3, tier:"major", since:"2019-01",
 sum:"Equity support for biotech startups that have completed proof of concept, bridging the gap until angel or VC money arrives.",
 ben:["Up to ₹30 lakh equity via a partner BioNEST incubator"],
 elig:["Post-PoC biotech startup incubated at one of 16 SEED partner incubators"],
 docs:["inc","deck","proto","cap","ip"],
 steps:["Get incubated at a BIRAC SEED partner (e.g., C-CAMP, IIT Bombay, IIT Delhi)","Apply through the incubator"],
 link:"https://www.birac.nic.in/seedFundNew.php",
 stacks:["big","leap"], verified:"Verified Sep 2026 (birac.nic.in)"
},
{
 id:"leap", name:"BIRAC LEAP Fund", abbr:"LEAP", body:"BIRAC (via partner incubators)",
 type:["equity"], stage:["early","growth"], sector:["bio"], amt:"Up to ₹100 lakh equity", amtL:100,
 student:false, dpiit:false, status:"calls", ease:3, tier:"more", since:"2019-01",
 sum:"Equity for biotech startups with a product close to commercialisation, to fund market launch and scale-up.",
 ben:["Up to ₹1 crore equity through a partner incubator"],
 elig:["Biotech startup with a product ready for commercialisation, incubated at a LEAP partner"],
 docs:["inc","deck","fin","cap","ip"],
 steps:["Apply via a LEAP partner incubator","Due diligence and investment committee"],
 link:"https://birac.nic.in",
 stacks:["birac-seed","rdi"], verified:"Standing scheme"
},
{
 id:"sbiri", name:"BIRAC SBIRI & BIPP (industry R&D)", abbr:"SBIRI / BIPP", body:"BIRAC",
 type:["grant","loan"], stage:["early","growth"], sector:["bio"], amt:"Grants + soft loans, sized by project", amtL:0,
 student:false, dpiit:false, status:"calls", ease:3, tier:"more", since:"2005-01",
 sum:"Cost-shared R&D funding for biotech companies: SBIRI for early-stage, higher-risk research by small firms, and BIPP for later-stage, high-impact product development.",
 ben:["Grants for early-stage R&D; soft loans for later stages","Access to BIRAC's validation and mentoring network"],
 elig:["Indian biotech companies (startups and SMEs) with in-house R&D"],
 docs:["inc","dpr","fin","ip"],
 steps:["Apply against an open BIRAC call","Expert review and site visit"],
 link:"https://birac.nic.in",
 stacks:["big","rdi"], verified:"Standing scheme"
},
{
 id:"birac-student", name:"BIRAC student programmes (SITARE-GYTI, E-YUVA)", abbr:"SITARE", body:"BIRAC",
 type:["grant","fellowship","challenge"], stage:["idea"], sector:["bio"], amt:"Up to ₹15 lakh (GYTI awards)", amtL:15,
 student:true, dpiit:false, status:"calls", ease:2, tier:"major", since:"2017-01",
 sum:"BIRAC's routes for students: SITARE-GYTI awards up to ₹15 lakh for outstanding student innovations, and E-YUVA centres offering fellowships and pre-incubation in universities.",
 ben:["Awards up to ₹15 lakh to take student projects forward","Fellowships and lab access via E-YUVA centres"],
 elig:["Students and young researchers in life sciences, engineering or medicine"],
 docs:["student","prop","edu"],
 steps:["Apply to the annual GYTI/SITARE call with your project","Or join an E-YUVA centre at a participating university"],
 link:"https://birac.nic.in",
 stacks:["big","prayas"], verified:"Amounts per BIRAC calls; confirm on the current call"
},
{
 id:"bioe3", name:"D.E.S.I.G.N. for BioE3 Challenge", abbr:"BioE3 Challenge", body:"Dept of Biotechnology",
 type:["challenge","grant"], stage:["idea"], sector:["bio","climate"], amt:"₹1 lakh–₹25 lakh", amtL:25,
 student:true, dpiit:false, status:"calls", ease:2, tier:"more", since:"2025-01",
 sum:"A DBT challenge under the BioE3 (Biotechnology for Economy, Environment and Employment) policy, rewarding students and startups for biomanufacturing and bio-based solutions.",
 ben:["Prizes and grants from ₹1 lakh to ₹25 lakh","Mentoring and incubation links"],
 elig:["Students, researchers and early startups"],
 docs:["prop","kyc","student"],
 steps:["Register for the current challenge round on the DBT site","Submit your design; shortlisted teams get support to build it"],
 link:"https://dbtindia.gov.in",
 stacks:["big","birac-student"], verified:"Listed as open in Sep 2026 (secondary source)"
},
{
 id:"shakti", name:"Biopharma SHAKTI", abbr:"SHAKTI", body:"Dept of Pharmaceuticals with DBT",
 type:["grant","equity"], stage:["early","growth"], sector:["bio"], amt:"₹10,000 cr over 5 years", amtL:0,
 student:false, dpiit:false, status:"announced", statusNote:"Announced in Budget 2026-27; guidelines and portal pending", ease:3, tier:"major", since:"2026-02",
 sum:"A Budget 2026-27 programme to build India's biologics and biosimilars industry: new NIPERs, 1,000+ accredited clinical-trial sites, a stronger drug regulator, and early-stage grants and equity for biopharma startups.",
 ben:["Early-stage grants and equity for biologics, biosimilars and cell & gene therapy","Access to clinical-trial networks and NIPER facilities"],
 elig:["Biopharma startups, MSMEs and research institutions (final criteria awaited)"],
 docs:["inc","dpr","ip"],
 steps:["Watch pharma-dept.gov.in for guidelines","Keep your DPR and regulatory plan ready"],
 link:"https://pharma-dept.gov.in",
 stacks:["prip","big"], verified:"Verified Sep 2026: not yet open"
},
{
 id:"prip", name:"PRIP — Research & Innovation in Pharma-MedTech", abbr:"PRIP", body:"Dept of Pharmaceuticals",
 type:["grant"], stage:["early","growth"], sector:["bio"], amt:"Up to ₹5 cr for startups", amtL:500,
 student:false, dpiit:false, status:"open", ease:3, tier:"major", since:"2025-10",
 sum:"A ₹5,000 crore scheme funding new medicines, complex generics, biosimilars and novel medical devices. Early-stage projects by startups get 100% funding on the first ₹1 crore and 50% beyond that, up to ₹5 crore.",
 ben:["Early-stage projects (up to ₹9 crore cost): up to ₹5 crore — 100% of the first ₹1 crore, 50% thereafter","Later-stage industry projects: up to ₹100 crore","Priority for rare diseases, AMR and outbreak pathogens"],
 elig:["Startups, MSMEs and companies in pharma and medtech; academia collaborations welcome"],
 docs:["inc","dpr","fin","ip"],
 steps:["Apply on the PRIP portal against the current call","Expert evaluation and approval"],
 link:"https://prip.pharma-dept.gov.in",
 stacks:["big","shakti"], verified:"Verified Sep 2026 (PIB, 1 Oct 2025 call)"
},
{
 id:"samridh", name:"MeitY SAMRIDH Accelerator", abbr:"SAMRIDH", body:"MeitY Startup Hub (via selected accelerators)",
 type:["equity","incubation"], stage:["early"], sector:["tech"], amt:"Up to ₹40 lakh", amtL:40,
 student:false, dpiit:true, status:"calls", ease:3, tier:"top", since:"2021-08",
 sum:"MeitY's accelerator programme for software product startups: up to ₹40 lakh matched with investment by the accelerator, plus customer connects and investor readiness.",
 ben:["Up to ₹40 lakh, matched by the accelerator's own investment","Structured acceleration, customer and investor access"],
 elig:["DPIIT-recognised software/IT product startup with an MVP or early traction","Selected through a SAMRIDH-partner accelerator"],
 docs:["dpiit","inc","deck","cap","fin"],
 steps:["Watch MeitY Startup Hub for SAMRIDH accelerator cohorts","Apply to a partner accelerator","Selection, then matched investment"],
 link:"https://msh.meity.gov.in/schemes/samridh",
 stacks:["tide","genesis","indiaai"], verified:"Verified Sep 2026 (secondary sources)"
},
{
 id:"tide", name:"MeitY TIDE 2.0", abbr:"TIDE 2.0", body:"MeitY (via TIDE 2.0 incubators)",
 type:["grant","fellowship","incubation"], stage:["idea","early"], sector:["tech"], amt:"EIR up to ₹4 L; grant up to ₹7 L", amtL:7,
 student:true, dpiit:false, status:"calls", ease:2, tier:"top", since:"2019-01",
 sum:"Early-stage support for tech startups using AI, IoT, blockchain and other ICT in areas like health, education, agriculture and fintech, through a national network of TIDE 2.0 incubators.",
 ben:["Entrepreneur-in-Residence support up to ₹4 lakh for idea/PoC stage","Grant up to ₹7 lakh for prototype stage","12 months of pre-incubation"],
 elig:["Indian citizens with an idea or PoC (EIR) or a working prototype (grant)","Company registration needed for the grant track"],
 docs:["kyc","prop","deck","inc"],
 steps:["Pick a TIDE 2.0 incubator (IITs, IIITs, universities) and apply to its call","Pitch and selection; funds released in tranches"],
 link:"https://msh.meity.gov.in/schemes/tide",
 stacks:["samridh","genesis","incubators"], verified:"Verified Sep 2026 (IIT Hyderabad TIDE page)"
},
{
 id:"genesis", name:"MeitY GENESIS (tier-2/3 startups)", abbr:"GENESIS", body:"MeitY Startup Hub",
 type:["grant","equity"], stage:["idea","early"], sector:["tech","deeptech"], amt:"From ₹10 lakh to ₹1 crore by track", amtL:100,
 student:true, dpiit:false, status:"calls", ease:3, tier:"major", since:"2022-07",
 sum:"Gen-Next Support for Innovative Startups: discovers and funds tech startups in tier-2 and tier-3 cities, with tracks from idea stage to pilots with a purchase order and deep tech.",
 ben:["EIR-style support for individual innovators (around ₹10 lakh)","Pilot support up to ₹40 lakh for startups with a purchase order","Deep-tech track up to ₹1 crore"],
 elig:["Tech startups and innovators based outside the big metros","Track-specific criteria (e.g., a valid PO for pilots)"],
 docs:["kyc","deck","prop","inc"],
 steps:["Apply via GENESIS partner incubators or the MSH portal when calls open"],
 link:"https://msh.meity.gov.in/schemes/genesis",
 stacks:["tide","samridh"], verified:"Amounts per secondary sources; confirm on the current call"
},
{
 id:"anic", name:"Atal New India Challenge (ANIC 2.0)", abbr:"ANIC", body:"Atal Innovation Mission, NITI Aayog",
 type:["grant","challenge"], stage:["early"], sector:["all","agri","climate","bio","space"], amt:"Up to ₹1 crore", amtL:100,
 student:false, dpiit:false, status:"calls", ease:3, tier:"top", since:"2022-01",
 sum:"Grants for startups with a working prototype that solves a listed national challenge — in health, water, agriculture, food processing, housing, energy, mobility or space — to take it to market over 12–18 months.",
 ben:["Up to ₹1 crore grant","Mentoring and access to AIM's ecosystem partners"],
 elig:["Indian startups/MSMEs with a prototype addressing a published challenge statement"],
 docs:["inc","prop","proto","deck","fin"],
 steps:["Read the sector challenges on the AIM site","Apply in the open ANIC round","Screening, jury pitch, then milestone-based grants"],
 link:"https://aim.gov.in/atal-new-india-challenge-2.0.php",
 stacks:["incubators","prayas"], verified:"Verified Sep 2026 (aim.gov.in); AIM extended to Mar 2028"
},
{
 id:"atl", name:"Atal Tinkering Labs (schools)", abbr:"ATL", body:"Atal Innovation Mission, NITI Aayog",
 type:["infrastructure"], stage:["idea"], sector:["all"], amt:"Maker labs in schools (₹20 lakh per school)", amtL:0,
 student:true, dpiit:false, status:"open", ease:1, tier:"more", since:"2016-01",
 sum:"Maker labs with 3D printers, electronics and robotics kits in schools across India, where students in Classes 6–12 can build projects and enter the ATL Marathon.",
 ben:["Free access to a maker lab at your school","ATL Marathon: top student innovations get incubation support"],
 elig:["Students of schools with an ATL"],
 docs:["student"],
 steps:["Ask your school's ATL in-charge to join","Enter the annual ATL Marathon with your team's project"],
 link:"https://aim.gov.in",
 stacks:["manak","sih"], verified:"AIM 2.0 approved to Mar 2028"
},
{
 id:"sih", name:"Smart India Hackathon 2026", abbr:"SIH", body:"Ministry of Education Innovation Cell & AICTE",
 type:["challenge"], stage:["idea"], sector:["all"], amt:"Cash prizes + incubation offers", amtL:1,
 student:true, dpiit:false, status:"calls", statusNote:"Internal hackathons Sep 2026; grand finale Dec 2026", ease:2, tier:"major", since:"2026-08",
 sum:"The national hackathon where student teams solve real problem statements from ministries and industry. Winning teams get prize money and many go on to incubation.",
 ben:["Prize money per problem statement for winners","Visibility with ministries and incubation opportunities"],
 elig:["Teams of 6 students from the same college, with at least one woman member","Selected through your institute's internal hackathon"],
 docs:["student"],
 steps:["Ask your college SPOC to register the institute","Win the internal hackathon","Submit your idea for online screening (Oct–Nov); finalists compete in December"],
 link:"https://sih.gov.in",
 stacks:["iic","prayas","eir"], verified:"Verified Sep 2026 (timeline)"
},
{
 id:"iic", name:"Institution's Innovation Council & National Innovation and Startup Policy", abbr:"IIC / NISP", body:"Ministry of Education Innovation Cell & AICTE",
 type:["incubation","support"], stage:["idea"], sector:["all"], amt:"Campus support: credits, IP help, startup leave", amtL:0,
 student:true, dpiit:false, status:"open", ease:1, tier:"more", since:"2019-01",
 sum:"Colleges with an IIC run bootcamps and pre-incubation. Under the National Innovation and Startup Policy, institutes can give academic credit for startup work, allow a semester or year off to run a startup, and help students file IP.",
 ben:["Academic credit and flexible attendance for startup work","Startup leave (a semester or year) with option to return","Pre-incubation, IP filing help and mentoring on campus"],
 elig:["Students of institutions that have an IIC and have adopted the policy"],
 docs:["student"],
 steps:["Contact your college's IIC or innovation cell","Ask what your institute's startup policy allows (credits, leave, IP share)"],
 link:"https://iic.mic.gov.in",
 stacks:["sih","prayas","eir"], verified:"Standing programme"
},
{
 id:"idex", name:"iDEX Defence Startup Challenges (DISC & Open Challenge)", abbr:"iDEX", body:"Innovations for Defence Excellence, Ministry of Defence",
 type:["grant","challenge","procurement"], stage:["idea","early"], sector:["defence","deeptech","space"], amt:"Up to ₹1.5 crore", amtL:150,
 student:false, dpiit:false, status:"deadline", deadline:"2026-09-30", statusNote:"iDEX Open Challenge 2026 closes 30 Sep 2026", ease:3, tier:"top", since:"2026-08",
 sum:"The Ministry of Defence's front door for startups. Solve a problem set by the armed forces, DRDO or defence PSUs and get a non-dilutive grant of up to ₹1.5 crore, trials with the users, and a path to procurement.",
 ben:["Grant up to ₹1.5 crore (no equity taken)","Direct access to Army, Navy, Air Force, DRDO and DPSUs for trials","Identified procurement pathway after success"],
 elig:["Indian startups, MSMEs and individual innovators (must incorporate before signing)"],
 docs:["inc","prop","deck","kyc","ip"],
 steps:["Browse challenges on the iDEX portal","Submit a technical proposal","Screening, pitch to the jury, then an SPARK grant agreement with milestones"],
 link:"https://idex.gov.in",
 stacks:["aditi","tdf","sipp"], verified:"Verified Sep 2026 (deadline 30 Sep 2026)"
},
{
 id:"aditi", name:"iDEX ADITI (deep-tech defence)", abbr:"ADITI", body:"Ministry of Defence",
 type:["grant"], stage:["early","growth"], sector:["defence","deeptech"], amt:"Up to ₹25 crore (50% of product budget)", amtL:2500,
 student:false, dpiit:true, status:"calls", ease:3, tier:"major", since:"2024-03",
 sum:"For critical and strategic defence technologies — AI, quantum, autonomous systems, satcom, semiconductors and cyber — ADITI funds up to half of a product development budget, to a maximum of ₹25 crore.",
 ben:["Grant up to 50% of product development budget, max ₹25 crore","Pathway to procurement by the armed forces"],
 elig:["DPIIT-recognised startups and MSMEs; individuals must form a startup before signing"],
 docs:["dpiit","inc","dpr","fin","ip"],
 steps:["Apply against ADITI challenges on the iDEX portal","Evaluation and pitch; milestone-based grant"],
 link:"https://www.ddpmod.gov.in/en/offerings/schemes-and-services/aditi_details",
 stacks:["idex","tdf"], verified:"Scheme period ran to FY2025-26; check iDEX for current ADITI rounds"
},
{
 id:"tdf", name:"DRDO Technology Development Fund", abbr:"TDF", body:"DRDO, Ministry of Defence",
 type:["grant"], stage:["early","growth"], sector:["defence","deeptech","manufacturing"], amt:"Up to ₹50 crore per project", amtL:5000,
 student:false, dpiit:false, status:"open", ease:3, tier:"major", since:"2022-06",
 sum:"DRDO funds Indian industry, especially MSMEs and startups, to develop defence technologies that are not yet made in India, with DRDO scientists as mentors.",
 ben:["Grant up to ₹50 crore per project","DRDO mentoring and test facilities"],
 elig:["Indian MSMEs and startups (can partner with academia)","Project must match a TDF-listed technology need"],
 docs:["inc","dpr","fin","udyam"],
 steps:["Check open topics on the TDF portal","Submit a proposal for the listed technology","Technical evaluation and project monitoring by DRDO"],
 link:"https://tdf.drdo.gov.in",
 stacks:["idex","aditi"], verified:"Verified Sep 2026 (limit raised to ₹50 cr, PIB 2022)"
},
{
 id:"d2d", name:"DRDO Dare to Dream Innovation Contest", abbr:"Dare to Dream", body:"DRDO",
 type:["challenge"], stage:["idea"], sector:["defence","deeptech"], amt:"Prizes up to ₹10 lakh", amtL:10,
 student:true, dpiit:false, status:"calls", ease:2, tier:"more", since:"2019-01",
 sum:"A contest for individuals and startups with ideas for emerging defence technologies. Winners receive cash prizes and a route into DRDO programmes.",
 ben:["Cash prizes (up to ₹10 lakh for startups)","Recognition and DRDO connections"],
 elig:["Indian individuals and startups"],
 docs:["prop","kyc"],
 steps:["Watch the DRDO site for the next edition","Submit your idea in the listed technology areas"],
 link:"https://www.drdo.gov.in",
 stacks:["idex"], verified:"Prize per recent editions; confirm on the next call"
},
{
 id:"inspace-seed", name:"IN-SPACe Seed Fund Scheme", abbr:"IN-SPACe Seed", body:"IN-SPACe, Dept of Space",
 type:["grant"], stage:["idea","early"], sector:["space"], amt:"Seed support for space startups (₹65 cr envelope)", amtL:100,
 student:false, dpiit:false, status:"open", statusNote:"Active FY2024-27; ₹3.3 cr disbursed by Jul 2026", ease:3, tier:"major", since:"2024-04",
 sum:"Seed funding for early space-tech startups to build proofs of concept and prototypes, with access to ISRO facilities and expertise through IN-SPACe.",
 ben:["Seed grants for PoC/prototype (per-startup support of up to about ₹1 crore)","Access to ISRO test facilities and technical mentoring"],
 elig:["Indian space-tech startups (non-governmental entities)"],
 docs:["inc","prop","deck","kyc"],
 steps:["Register on the IN-SPACe portal","Apply under the seed fund call","Evaluation by IN-SPACe technical committee"],
 link:"https://www.inspace.gov.in",
 stacks:["space-vc","taf"], verified:"Verified Sep 2026 (Parliament reply, Aug 2026)"
},
{
 id:"taf", name:"IN-SPACe Technology Adoption Fund", abbr:"TAF", body:"IN-SPACe, Dept of Space",
 type:["grant"], stage:["early","growth"], sector:["space"], amt:"₹500 cr fund; up to ₹25 cr per project", amtL:2500,
 student:false, dpiit:false, status:"open", ease:3, tier:"more", since:"2025-02",
 sum:"Co-funds space companies to take technologies to commercial products — covering a share of project cost for startups and MSMEs.",
 ben:["Up to 60% of project cost for startups and MSMEs (40% for larger companies)","Up to ₹25 crore per project"],
 elig:["Indian non-governmental space entities with a technology ready to commercialise"],
 docs:["inc","dpr","fin","ip"],
 steps:["Apply on the IN-SPACe TAF page","Evaluation and milestone-based support"],
 link:"https://www.inspace.gov.in/inspace?id=inspace_taf",
 stacks:["inspace-seed","space-vc"], verified:"Verified Sep 2026 (launch Feb 2025; Parliament reply Aug 2026)"
},
{
 id:"space-vc", name:"Space Sector Venture Capital Fund", abbr:"Space VC Fund", body:"IN-SPACe (managed by SIDBI Venture Capital)",
 type:["equity"], stage:["early","growth"], sector:["space"], amt:"₹1,000 cr fund", amtL:0,
 student:false, dpiit:false, status:"open", ease:3, tier:"major", since:"2025-10",
 sum:"A ₹1,000 crore government VC fund investing only in Indian space startups, from early stage to growth. SEBI approval came in October 2025 and it has already invested about ₹189 crore.",
 ben:["Equity investment in space startups","Signals credibility to co-investors"],
 elig:["Indian space-tech startups with a scalable technology"],
 docs:["inc","deck","fin","cap"],
 steps:["Pitch the fund manager (SIDBI Venture Capital)","Due diligence and investment committee"],
 link:"https://www.inspace.gov.in",
 stacks:["inspace-seed","taf","fof2"], verified:"Verified Sep 2026 (Parliament reply, Aug 2026)"
},
{
 id:"rkvy", name:"RKVY Agri-Startup Programme (formerly RKVY-RAFTAAR)", abbr:"RKVY", body:"Ministry of Agriculture (via 24 R-ABIs and 5 knowledge partners)",
 type:["grant","incubation"], stage:["idea","early"], sector:["agri"], amt:"₹5 L (idea) + ₹25 L (seed)", amtL:30,
 student:true, dpiit:false, status:"calls", ease:2, tier:"top", since:"2018-01",
 sum:"The main central grant for agritech and allied startups — precision farming, farm machinery, food tech, supply chain, dairy, fisheries — delivered through agribusiness incubators at agricultural universities and institutes.",
 ben:["Up to ₹5 lakh at idea/pre-seed stage","Up to ₹25 lakh at seed stage","Incubation, training and mentoring"],
 elig:["Agri and allied-sector startups and entrepreneurs, selected by an R-ABI or knowledge partner (e.g., MANAGE, NIAM, IARI)"],
 docs:["prop","kyc","inc","deck"],
 steps:["Find the R-ABI or knowledge partner near you","Apply to its cohort call","Training programme, then pitch for the grant"],
 link:"https://rkvystartups.nic.in/",
 stacks:["agrisure","aif","pmfme"], verified:"Verified Sep 2026 (programme page)"
},
{
 id:"agrisure", name:"AgriSURE Fund", abbr:"AgriSURE", body:"NABARD (NABVENTURES) with Ministry of Agriculture",
 type:["equity"], stage:["early","growth"], sector:["agri","climate"], amt:"Tickets up to ~₹25 cr", amtL:2500,
 student:false, dpiit:false, status:"open", ease:3, tier:"major", since:"2024-09",
 sum:"A blended fund for agri and rural startups: it invests in agri-focused AIFs and also directly in startups, from early stage to Series A.",
 ben:["Equity or equity-linked investment","Fund-of-funds route via agri-focused VC funds and a direct investment window"],
 elig:["Startups in agriculture, allied sectors and rural enterprise with a scalable model"],
 docs:["inc","deck","fin","cap"],
 steps:["Apply through the NABVENTURES AgriSURE page","Or pitch an AgriSURE-backed AIF"],
 link:"https://nabventures.in/agrisure.aspx",
 stacks:["rkvy","fof2"], verified:"Verified Sep 2026 (₹200 cr approvals by early 2026)"
},
{
 id:"aif", name:"Agriculture Infrastructure Fund", abbr:"AIF (Agri)", body:"Ministry of Agriculture",
 type:["loan","subsidy","guarantee"], stage:["early","growth"], sector:["agri"], amt:"Loans up to ₹2 cr with 3% interest subvention", amtL:200,
 student:false, dpiit:false, status:"open", ease:2, tier:"more", since:"2020-07",
 sum:"Cheaper, guaranteed loans for post-harvest and farm infrastructure — warehouses, cold chains, sorting and grading units, primary processing — which agri startups can use too.",
 ben:["3% annual interest subvention on loans up to ₹2 crore","Credit guarantee cover on eligible loans"],
 elig:["Agri-entrepreneurs, startups, FPOs, cooperatives and companies building eligible farm infrastructure"],
 docs:["dpr","inc","bank","land","quote"],
 steps:["Apply on the AIF portal","Your chosen bank appraises and sanctions the loan"],
 link:"https://agriinfra.dac.gov.in",
 stacks:["rkvy","pmfme"], verified:"Standing scheme"
},
{
 id:"pmfme", name:"PM Formalisation of Micro Food Processing Enterprises", abbr:"PMFME", body:"Ministry of Food Processing Industries",
 type:["subsidy","loan"], stage:["idea","early"], sector:["agri"], amt:"35% subsidy, up to ₹10 lakh", amtL:10,
 student:false, dpiit:false, status:"deadline", deadline:"2026-09-30", statusNote:"Valid till 30 Sep 2026; 5-year extension proposed", ease:2, tier:"major", since:"2020-06",
 sum:"A credit-linked capital subsidy for small food businesses — pickles, bakery, millets, spices, dairy products — to buy machinery and upgrade.",
 ben:["35% credit-linked subsidy on project cost, up to ₹10 lakh per unit","Branding, marketing and training support"],
 elig:["Micro food processing units (individuals, proprietors, partnerships, FPOs, SHGs)"],
 docs:["dpr","kyc","bank","quote","udyam"],
 steps:["Apply on the PMFME portal (District Resource Persons help prepare the DPR)","Bank sanctions the loan; subsidy is credited to the loan account"],
 link:"https://pmfme.mofpi.gov.in",
 stacks:["mudra","pmegp","udyam"], verified:"Verified Sep 2026 (Business Standard, Aug 2026)"
},
{
 id:"cgtmse", name:"CGTMSE Collateral-Free MSME Loans", abbr:"CGTMSE", body:"Credit Guarantee Fund Trust for Micro & Small Enterprises (MSME Ministry & SIDBI)",
 type:["guarantee","loan"], stage:["early","growth"], sector:["all"], amt:"Collateral-free loans up to ₹10 cr", amtL:1000,
 student:false, dpiit:false, status:"open", ease:1, tier:"top", since:"2025-04",
 sum:"Banks lend to micro and small enterprises without collateral or third-party guarantees because CGTMSE covers most of the risk. The limit rose to ₹10 crore from April 2025.",
 ben:["Guarantee on loans up to ₹10 crore without collateral","Covers term loans and working capital"],
 elig:["New or existing micro and small enterprises (manufacturing or services) with Udyam registration","Loan from a member lending institution"],
 docs:["udyam","dpr","kyc","bank","fin"],
 steps:["Approach any bank or NBFC that is a CGTMSE member lending institution","Ask for the loan to be covered under CGTMSE","The lender pays the guarantee fee (usually recovered from you)"],
 link:"https://www.cgtmse.in",
 stacks:["udyam","pmegp","mudra"], verified:"Verified Sep 2026 (scheme document as of 1 Apr 2025)"
},
{
 id:"pmegp", name:"Prime Minister's Employment Generation Programme", abbr:"PMEGP", body:"Ministry of MSME (via KVIC, KVIB and DICs)",
 type:["subsidy","loan"], stage:["idea"], sector:["all","manufacturing"], amt:"15–35% subsidy on projects up to ₹50 L", amtL:50,
 student:true, dpiit:false, status:"open", ease:2, tier:"top", since:"2008-08",
 sum:"A capital subsidy on bank loans for new micro enterprises: up to ₹50 lakh project cost for manufacturing and ₹20 lakh for services, with 15–35% of the cost given as margin money subsidy.",
 ben:["Subsidy of 15% (urban) or 25% (rural) for general category; 25–35% for special categories","Second loan for upgrading successful units: up to ₹1 crore (manufacturing) with 15–20% subsidy"],
 elig:["Individuals aged 18+; Class 8 pass for projects above ₹10 lakh (manufacturing) / ₹5 lakh (services)","New units only; one person per family"],
 docs:["dpr","kyc","edu","bank","quote"],
 steps:["Apply online on the PMEGP e-portal","KVIC/DIC task force interview; bank sanctions the loan","Complete the entrepreneurship training; subsidy is adjusted after 3 years"],
 link:"https://www.kviconline.gov.in/pmegpeportal",
 stacks:["cgtmse","udyam","mudra"], verified:"Verified Sep 2026 (current parameters)"
},
{
 id:"mudra", name:"PM Mudra Yojana (incl. Tarun Plus)", abbr:"Mudra", body:"Dept of Financial Services (via banks, NBFCs, MFIs)",
 type:["loan"], stage:["idea","early"], sector:["all"], amt:"Collateral-free loans ₹50,000–₹20 lakh", amtL:20,
 student:true, dpiit:false, status:"open", ease:1, tier:"top", since:"2024-10",
 sum:"Small collateral-free business loans in four tiers: Shishu (up to ₹50,000), Kishore (up to ₹5 lakh), Tarun (up to ₹10 lakh) and Tarun Plus (₹10–20 lakh) for those who have repaid a Tarun loan.",
 ben:["No collateral required","Tarun Plus up to ₹20 lakh for good repayers"],
 elig:["Non-farm income-generating micro enterprises: manufacturing, trading, services and allied agriculture"],
 docs:["kyc","dpr","bank","quote"],
 steps:["Apply at any bank branch, NBFC or MFI, or on the Udyamimitra portal","Loan sanctioned after appraisal"],
 link:"https://www.mudra.org.in",
 stacks:["pmegp","cgtmse"], verified:"Verified Sep 2026"
},
{
 id:"msme-innov", name:"MSME Innovative Scheme (Incubation, IPR, Design)", abbr:"MSME Innovative", body:"Ministry of MSME (via host institutes)",
 type:["grant","ipr"], stage:["idea","early"], sector:["all","manufacturing"], amt:"Up to ₹15 L per idea; IPR up to ₹5 L", amtL:15,
 student:true, dpiit:false, status:"open", ease:2, tier:"major", since:"2022-03",
 sum:"Three tools in one: grants to develop ideas at host institutes (incubation), reimbursement of IP registration costs, and co-funding of professional product design — all run through the MSME Champions portal.",
 ben:["Incubation: up to ₹15 lakh per idea via a host institute","IPR: reimbursement up to ₹5 lakh (foreign patent), ₹1 lakh (domestic patent), smaller amounts for trademarks and designs","Design: co-funding of design projects with NID, IITs and other design institutes"],
 elig:["Innovators and students (incubation, via host institutes)","Udyam-registered MSMEs (IPR and design components)"],
 docs:["prop","kyc","udyam","ip","fees"],
 steps:["Register on the MSME Innovative module of the Champions portal","For incubation, submit your idea to a host institute","For IPR, file first and then claim reimbursement with fee receipts"],
 link:"https://innovative.msme.gov.in",
 stacks:["sipp","udyam","pmegp"], verified:"Guidelines on the MSME portal; amounts per 2022 guidelines"
},
{
 id:"udyam", name:"Udyam (MSME) Registration", abbr:"Udyam", body:"Ministry of MSME",
 type:["compliance"], stage:["idea","early","growth"], sector:["all"], amt:"Free · unlocks MSME benefits", amtL:0,
 student:false, dpiit:false, status:"open", ease:1, tier:"major", since:"2020-07",
 sum:"The free, paperless MSME registration using your Aadhaar and PAN. You need it for CGTMSE, PMEGP-linked support, MSME procurement preferences, delayed-payment protection and TReDS.",
 ben:["Access to MSME credit guarantees, subsidies and public procurement preferences","Protection against delayed payments (buyers must pay within 45 days)"],
 elig:["Any micro, small or medium enterprise"],
 docs:["kyc","pan"],
 steps:["Go to the Udyam portal and enter the proprietor's/director's Aadhaar","Fill in PAN and business details; the certificate is issued online"],
 link:"https://udyamregistration.gov.in",
 stacks:["cgtmse","treds","procure"], verified:"Standing"
},
{
 id:"mcgs", name:"Mutual Credit Guarantee Scheme for MSMEs", abbr:"MCGS-MSME", body:"Dept of Financial Services & NCGTC",
 type:["guarantee","loan"], stage:["growth"], sector:["manufacturing"], amt:"60% guarantee on equipment loans up to ₹100 cr", amtL:10000,
 student:false, dpiit:false, status:"open", statusNote:"Modified 21 Mar 2026 (exporters: 75% cover)", ease:2, tier:"more", since:"2026-03",
 sum:"For manufacturing MSMEs buying plant and machinery: a 60% government guarantee on loans up to ₹100 crore, making big equipment purchases bankable. Exporters get 75% cover.",
 ben:["60% guarantee on loans up to ₹100 crore; 75% for eligible exporters (up to ₹20 crore)","Equipment need be only 60% of project cost (was 75%)"],
 elig:["Udyam-registered MSMEs; exporters need 25%+ export share for 3 years"],
 docs:["udyam","dpr","fin","quote"],
 steps:["Apply through your lender, which seeks NCGTC cover"],
 link:"https://www.ncgtc.in",
 stacks:["cgtmse","udyam"], verified:"Verified Sep 2026 (PIB, 21 Mar 2026)"
},
{
 id:"treds", name:"TReDS Invoice Discounting", abbr:"TReDS", body:"RBI-licensed platforms (policy by Ministry of Finance & MSME)",
 type:["loan"], stage:["early","growth"], sector:["all"], amt:"Get paid on invoices in days", amtL:0,
 student:false, dpiit:false, status:"open", ease:1, tier:"more", since:"2026-02",
 sum:"Sell your invoices on large buyers — companies, PSUs, government — to financiers on a TReDS platform and get cash in days instead of waiting 60–90 days. Budget 2026-27 made TReDS mandatory for central PSU purchases from small firms and added a CGTMSE guarantee.",
 ben:["Fast, collateral-free working capital against invoices","Budget 2026: TReDS mandatory for CPSE purchases; linked with GeM"],
 elig:["Udyam-registered MSMEs selling to buyers registered on TReDS"],
 docs:["udyam","pan","bank"],
 steps:["Register on a TReDS platform (RXIL, M1xchange, Invoicemart and others)","Upload invoices accepted by your buyer; financiers bid"],
 link:"https://www.rbi.org.in",
 stacks:["udyam","procure","cgtmse"], verified:"Verified Sep 2026 (Budget 2026-27)"
},
{
 id:"sri-fund", name:"Self-Reliant India (SRI) Fund", abbr:"SRI Fund", body:"Ministry of MSME (NSIC Venture Capital Fund)",
 type:["equity"], stage:["growth"], sector:["all","manufacturing"], amt:"₹50,000 cr fund-of-funds; ₹2,000 cr top-up in 2026", amtL:0,
 student:false, dpiit:false, status:"open", ease:3, tier:"more", since:"2026-02",
 sum:"A mother fund that invests in daughter funds, which provide equity to MSMEs with growth potential. Budget 2026-27 added ₹2,000 crore to keep risk capital flowing to micro enterprises.",
 ben:["Growth equity for MSMEs via SEBI-registered daughter funds"],
 elig:["Udyam-registered MSMEs with scalable businesses"],
 docs:["udyam","fin","deck","cap"],
 steps:["Pitch daughter funds empanelled under the SRI Fund"],
 link:"https://msme.gov.in",
 stacks:["sme-growth","cgtmse"], verified:"Top-up verified (PIB, Budget 2026-27)"
},
{
 id:"sme-growth", name:"SME Growth Fund", abbr:"SME Growth Fund", body:"Ministry of Finance / MSME",
 type:["equity"], stage:["growth"], sector:["all","manufacturing"], amt:"₹10,000 cr", amtL:0,
 student:false, dpiit:false, status:"announced", statusNote:"Announced in Budget 2026-27; operating guidelines awaited", ease:3, tier:"more", since:"2026-02",
 sum:"A ₹10,000 crore fund announced in Budget 2026-27 to create 'future champions' by giving equity and quasi-equity to high-performing SMEs selected on set criteria.",
 ben:["Equity/quasi-equity for fast-growing SMEs"],
 elig:["Criteria to be notified"],
 docs:["udyam","fin"],
 steps:["Watch the MSME Ministry for guidelines"],
 link:"https://msme.gov.in",
 stacks:["sri-fund"], verified:"Verified Sep 2026: not yet operational"
},
{
 id:"zed", name:"ZED Certification Subsidy", abbr:"ZED", body:"Ministry of MSME",
 type:["subsidy"], stage:["early","growth"], sector:["manufacturing"], amt:"Up to 80% of certification cost", amtL:0,
 student:false, dpiit:false, status:"open", ease:1, tier:"more", since:"2022-04",
 sum:"Zero Defect Zero Effect certification signals quality to buyers. The government pays most of the certification cost (80% for micro, 60% for small, 50% for medium enterprises).",
 ben:["80/60/50% subsidy on certification cost","Bronze level certification is fully subsidised after taking the ZED pledge"],
 elig:["Udyam-registered manufacturing MSMEs"],
 docs:["udyam"],
 steps:["Take the ZED pledge on the ZED portal","Apply for Bronze, Silver or Gold certification"],
 link:"https://zed.msme.gov.in",
 stacks:["udyam","procure"], verified:"Standing scheme"
},
{
 id:"smile", name:"SIDBI SMILE Soft Loans", abbr:"SMILE", body:"SIDBI",
 type:["loan"], stage:["growth"], sector:["manufacturing"], amt:"Soft-term loans from ₹10 lakh", amtL:0,
 student:false, dpiit:false, status:"open", ease:2, tier:"more", since:"2015-01",
 sum:"The Make in India Soft Loan Fund for MSMEs: quasi-equity style soft loans to help manufacturing and service MSMEs meet debt-equity requirements for expansion.",
 ben:["Soft loans on relaxed terms to support the promoter's contribution"],
 elig:["MSMEs in manufacturing and services, especially Make in India sectors"],
 docs:["udyam","fin","dpr"],
 steps:["Apply to SIDBI directly or through its online portal"],
 link:"https://www.sidbi.in",
 stacks:["cgtmse","mcgs"], verified:"Listed open Sep 2026"
},
{
 id:"mitras", name:"Corporate Mitras (compliance help)", abbr:"Corporate Mitras", body:"Ministry of Finance with ICAI, ICSI, ICMAI",
 type:["support"], stage:["idea","early"], sector:["all"], amt:"Affordable compliance support", amtL:0,
 student:false, dpiit:false, status:"announced", statusNote:"Announced in Budget 2026-27", ease:1, tier:"more", since:"2026-02",
 sum:"A Budget 2026-27 plan to train a cadre of para-professionals, especially in tier-2 and tier-3 towns, who help small firms with compliance at low cost.",
 ben:["Low-cost help with filings and compliance"],
 elig:["Small businesses and startups (details awaited)"],
 docs:[],
 steps:["Watch for rollout via ICAI, ICSI and ICMAI"],
 link:"https://www.indiabudget.gov.in",
 stacks:["udyam"], verified:"Announced; not yet rolled out"
},
{
 id:"rail", name:"Rail Tech Policy (Startups for Railways)", abbr:"Rail Tech", body:"Ministry of Railways",
 type:["grant","procurement"], stage:["early","growth"], sector:["rail","deeptech"], amt:"Up to 50% of project cost + order pipeline", amtL:0,
 student:false, dpiit:false, status:"open", ease:2, tier:"major", since:"2026-02",
 sum:"Launched 27 Feb 2026, modelled on iDEX: a 24×7 Rail Tech portal where startups propose solutions to Railways' problems (safety, AI, drones, track and stress monitoring). Railways funds up to half the project and promises large orders after success.",
 ben:["Up to 50% funding of approved projects","Prototype and scale-up grants raised (prototype limits doubled, scale-up more than tripled)","Long-term orders for successful solutions"],
 elig:["Startups, innovators and institutions solving a listed Railways problem"],
 docs:["inc","prop","deck"],
 steps:["Browse problem statements on the Rail Tech portal","Submit a single-stage detailed proposal","Evaluation, trials and scale-up"],
 link:"https://indianrailways.gov.in",
 stacks:["idex","procure"], verified:"Verified Sep 2026 (launch coverage, Feb 2026)"
},
{
 id:"great", name:"GREAT — Technical Textiles Startups", abbr:"GREAT", body:"Ministry of Textiles (National Technical Textiles Mission)",
 type:["grant"], stage:["idea","early"], sector:["manufacturing"], amt:"Up to ₹50 lakh", amtL:50,
 student:true, dpiit:false, status:"calls", ease:2, tier:"more", since:"2023-01",
 sum:"Grant for Research & Entrepreneurship across Aspiring Innovators in Technical Textiles: funds students and startups turning technical-textile ideas (medical, protective, agro, geo textiles) into products.",
 ben:["Grant up to ₹50 lakh per startup","Mentoring via partner institutes"],
 elig:["Individuals, students and startups working on technical textiles"],
 docs:["prop","kyc","inc"],
 steps:["Apply through the Ministry of Textiles call","Evaluation by the empowered programme committee"],
 link:"https://texmin.nic.in",
 stacks:["msme-innov"], verified:"Grants of ₹50 lakh approved in 2024-25 rounds"
}
];
